name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '35 * * * *'

jobs:
  if_merged:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build
          run : "gcc -o Output.exe main.c -O2"
        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v4
          with:
            name: Output
            path: Output.exe
            retention-days: 5
        
permissions:
   contents: write
   pull-requests: write
   actions: write

#测试
