name: SYNC

on:
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: yituodab
          base: main
          head: main
permissions:
   contents: write
   pull-requests: write
   actions: write
